#!/usr/bin/env bash

WALL_DIR="$HOME/Wallpapers"
THUMB_DIR="$HOME/.cache/wallthumbs"
mkdir -p "$THUMB_DIR"

# Generate Rofi entries from existing thumbnails
entries=""
while IFS= read -r img; do
    name="$(basename "$img")"
    hash="$(sha1sum <<< "$img" | awk '{print $1}')"
    thumb="$THUMB_DIR/$hash.jpg"

    entries+="$name\x00icon\x1f$thumb\n"
done < <(find "$WALL_DIR" -type f \( -iname '*.jpg' -o -iname '*.png' -o -iname '*.jpeg' \))

# Run rofi to select
chosen=$(printf "$entries" | wofi --show dmenu)

# Set selected wallpaper
if [ -n "$chosen" ]; then
    full=$(find "$WALL_DIR" -type f -name "$chosen" | head -n1)
    matugen image "$full"
    swww img "$full" --transition-fps 60 --transition-type random
fi 

# Update hyprlock.conf (not needed now as matugen vars fix this issue)
# wallpath=$(swww query | grep -oP 'image: \K.*')
# sed -i "s|^ *path = .*|    path = $wallpath|" ~/.config/hypr/hyprlock.conf

hyprctl reload
